name: example
description: An example on how to use Fast Flutter Driver

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  fast_flutter_driver: 3.0.0
  test: ^1.16.4
  driver_extensions: ^2.0.0-nullsafety.1


flutter:
  uses-material-design: true

dependency_overrides:
  args: ^2.0.0
  fast_flutter_driver:
    path: ../driver
