name: example
description: An example on how to use Fast Flutter Driver

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  random_color: ^1.0.3

dev_dependencies:
  flutter_driver:
    sdk: flutter
  fast_flutter_driver:
    git:
      url: git://github.com/tomaszpolanski/fast_flutter_driver.git
      path: driver
  fast_flutter_driver_tool:
    git:
      url: git://github.com/tomaszpolanski/fast_flutter_driver.git
      path: tool


flutter:
  uses-material-design: true
