name: fast_flutter_driver
description: Toolkit for running rapidly flutter driver tests on desktopÂ .
version: 0.0.1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  mockito: ^4.1.1
  csv: ^4.0.0
  test: ^1.9.4
  args: ^1.5.1
  process_run: ^0.10.0+1
  colorize: 2.0.0
  window_utils:
    git:
      url: git://github.com/tomaszpolanski/window-utils.git
      ref: disabling-linux-support




