name: fast_flutter_driver_tool
description: Toolkit for running rapidly flutter driver tests on desktop.
version: 0.0.5+1
homepage: https://github.com/tomaszpolanski/fast_flutter_driver

environment:
  sdk: '>=2.6.0 <3.0.0'

executables:
  fastdriver: main

dependencies:
  args: ^1.5.1
  process_run: ^0.10.0+1
  colorize: ^2.0.0
  meta: ^1.1.8
  cli_util: ^0.1.3+2

dev_dependencies:
  test: ^1.6.3