name: fast_flutter_driver_tool
description: Toolkit for running rapidly flutter driver tests on desktop.
version: 0.0.1
homepage: https://github.com/tomaszpolanski/fast_flutter_driver

environment:
  sdk: '>=2.7.0 <3.0.0'

executables:
  fastdriver: main

dependencies:
#  flutter:
#    sdk: flutter
  mockito: ^4.1.1
  csv: ^4.0.0
  test: ^1.9.4
  args: ^1.5.1
  process_run: ^0.10.0+1
  colorize: ^2.0.0
  meta: ^1.1.8
#  window_utils:
#    git:
#      url: git://github.com/tomaszpolanski/window-utils.git
#      ref: disabling-linux-support


