name: fast_flutter_driver_tool
description: Toolkit for running rapidly flutter driver tests on desktop.
version: 2.0.0-nnbd
homepage: https://github.com/tomaszpolanski/fast_flutter_driver

environment:
  sdk: '>=2.10.0-18.0 <3.0.0'

executables:
  fastdriver: main

dependencies:
  args: ^1.5.1
  cli_util: ^0.2.0
  colorize: ^2.0.0
  http: ^0.12.0+4
  meta: ^1.1.8
  path: ^1.6.4
  process_run: ^0.10.0+1
  yaml: ^2.2.0

dev_dependencies:
  test: ^1.6.3
  mockito: ^4.1.1
  coverage: ^0.14.0
  file: ^5.1.0

