name: fast_flutter_driver
description: Toolkit for running rapidly flutter driver tests on desktop.
version: 1.3.0
homepage: https://github.com/tomaszpolanski/fast_flutter_driver

environment:
  sdk: '>=2.9.0-18.0 <3.0.0'
  flutter: ">=1.12.8 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  args: ^1.5.1
  colorize: ^2.0.0
  csv: ^4.0.0
  fast_flutter_driver_tool: ^1.4.0
  meta: ^1.1.8
  mockito: ^4.1.1
  process_run: ^0.10.0+1
  test: ^1.9.4
  win32: ^1.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: WindowUtils


dependency_overrides:
  fast_flutter_driver_tool:
    git:
      url: git://github.com/tomaszpolanski/fast_flutter_driver.git
      ref: nnbd
      path: tool