name: fast_flutter_driver
description: Toolkit for running rapidly flutter driver tests on desktop.
version: 0.1.0
homepage: https://github.com/tomaszpolanski/fast_flutter_driver

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  mockito: ^4.1.1
  csv: ^4.0.0
  test: ^1.9.4
  args: ^1.5.1
  process_run: ^0.10.0+1
  colorize: ^2.0.0
  meta: ^1.1.8
  window_utils:
    path: ./dependencies/window-utils
  fast_flutter_driver_tool: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
